// <auto-generated />
namespace StudyBasedApplication.Data.EFRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class lakhan_kamala : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lakhan_kamala));
        
        string IMigrationMetadata.Id
        {
            get { return "201411051234589_lakhan_kamala"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
